### ISSUE TITLE
rgbの値が範囲外だった場合に代入する値を統一する。

### ISSUE THREAD

**Issue by subarunrun0812** [subarunrun0812/42-Cub3D#121]

**Comment by subarunrun0812** [comment]
create_rgb()のred,green,blueが範囲外だった場合に0を代入していると思いますが、その値を統一したいです。
missing_rgb_argument()では、255を代入しているので、その辺も決めていきたいです。

**Comment by hno-guchi** [comment]
static unsigned int	create_rgb(int r, int g, int b)
{
	unsigned int	rgb;

	rgb = 0;
	if (r < 0 || 255 < r)
	{
		r = 0;
	}
	if (g < 0 || 255 < g)
	{
		g = 0;
	}
	if (b < 0 || 255 < b)
	{
		b = 0;
	}
	rgb |= (r & 0xFF) << 16;
	rgb |= (g & 0xFF) << 8;
	rgb |= (b & 0xFF);
	return (rgb);
}
私の場合は、０

**Comment by hno-guchi** [comment]
２５５で統一します！

**Comment by subarunrun0812** [comment]
了解です！ありがとうございます！
